import { BankCode } from './base.interface'

export interface SearchParams extends PageParams {
  url: string
}

export interface PageParams {
  pageSize: number
  pageNo: number
}

export interface ListPage {
  currentPage: number
  pageSize: number
}

export interface SearchOneParams {
  id: number
}
export interface FixedSearchParams {
  url: string
}

export interface GetCodeParams {
  userName: string
  password: string
  redirectUri?: string
}

export interface LoginCodeParams {
  code: string
}
export interface SendSmsParams {
  captcha?: string
  captchaId?: string
  mobile: string
}
export interface ValidateImageCodeParams {
  captcha: string
  captchaId: string
}

export interface RegisterSendSmsParams extends ValidateImageCodeParams {
  tel: string
}

export interface GetCustomerScoreParams {
  customerId: number
  paperId: string
}
export interface FindPwdSendSmsParams extends ValidateImageCodeParams {
  phoneNumber: string
}
export interface FindPwdPhonesParams {
  userPhone: string
  captchaId: string
  newPwd: string
  reNewPwd: string
  smsCode: string
}

export interface BorrowListParams extends ListPage {
  borrowType?: number
  borrowStatus?: number
  borrowTimeLimit?: number
  annualInterestRate?: number
  annualInterestRateSort?: number
  borrowTimeLimitSort?: number
  borrowChannel?: number
  tenderStatus?: number
}
// Generated by https://quicktype.io

export interface RegistersByCodeParams {
  userType: 'user' | 'corp'
  userPhone: string
  customerPassword: string
  invitePhone: string
  smsCode: string
  captchaId: string
  busiCode: string
}

export interface QuestionListParams {
  customerId: number
  paperId: string
}

// Generated by https://quicktype.io

export interface AddOrUpCustRiskAsseParams {
  customerId: number
  paperId: string
  selAndAnwsers: SelAndAnwser[]
}

export interface SelAndAnwser {
  anwserId: number
  selectedId: number
  questionSelectId: number
}

export interface ExchangeAwardParams {
  integralAwardId: number
  consigneeId?: number
}

export interface ConsigneeBase {
  consigneeName: number
  consigneePhone: number
  consigneeStatus: number
  consigneePro: string
  consigneeCity: string
  consigneeAddress: number
}

export interface AddConsigneeParams extends ConsigneeBase {}
export interface UpdateConsigneeParams extends ConsigneeBase {
  id?: number
}

export interface IntegralDetailedParams extends ListPage {
  acquireType: number
  dataOption: number
}

export interface AuthUrlParams {
  reURL: string
  channelCode: BankCode
}

export interface AccountRechargePageListParams extends ListPage {
  channelCode: BankCode
}

export interface SaveAccountRechargeParams {
  rechargeMoney: number
  reURL: string
  channelCode: BankCode
}
export interface UserLoginParams {
  loginRedirectStrategy?: string
  channelCode: BankCode
}

export interface AccountCashPageListParams extends ListPage {
  channelCode: BankCode
}
export interface QueryCashAccountParams {
  channelCode: BankCode
}

export interface SaveAccountCashParams {
  cashTotal: number
  isIntegrals: number
  reURL: string
  channelCode: BankCode
}

export interface MessageCenterListParams extends ListPage {}
export interface MessageCenterEditParams {
  messageId: string
}
export interface UserCashRecordParams extends ListPage {}

export interface CustomerCouponTypeListParams extends ListPage {
  couponType: number
  couponStatus: number
}

export interface HobbyAddAndUpdateParams {
  hobbies: string
}

export interface UpdatePhoneSendMessageParams {
  oldPhone: string
  captcha: string
  captchaId: string
  type: string
  newPhone?: string
}
export interface VerificationUpdatePhoneMessageParams {
  smsCode: string
  newPhone: string
}

export interface VerificationMessageParmas {
  smsCode: string
}

export interface CheckPwdParams {
  pwd: string
}
export interface AccountUpdatePwdParams {
  newPwd: string
  againNewPwd: string
}

export interface AccountUpdatePwdSendMessageParams {
  pwd: string
  captcha: string
  captchaId: string
}

export interface OtherBorrowingsParams {
  isLoansOthers: string
  loansOthersMoney: string
}

export interface BorrowInfoParams {
  borrowNo: string
}
export interface BorrowOtherInfoParams extends ListPage {
  borrowNo: string
}

export interface UserCouponListParams extends ListPage {
  borrowNo: number
  investAmount: number
}

export interface SaveTenderBorrowParams {
  tenderType: number
  borrowNo: number
  tenderAmount: number
  ddjId?: number
  jxjId?: number
  reURL: string
  channelCode: BankCode
}

export interface MyloanParams {
  channelCode: BankCode
}

export interface AddBorrowApplyParams {
  customerId: number
  factorId: number
  legalRepresentative: string
  registerPhone: string
  registerDate: string
  registerMoney: number
  registerAddress: string
  applyNo: number
  applyAmount: number
  applyRepaymentTime: string
  applyContent: string
  uploadImg: string
}

export interface UploadImgItem {
  id: any
  name: any
  bucket: any
}

export interface LoanStateParams {
  id: number
}
export interface GetOldAccountCashInfoParams {
  oldBankAccount: string
  oldCardNumber: string
  oldCustomerPhone: string
  oldCustomerRealname: string
}
export interface UpdateOldAccountCashParams {
  oldCustomerPhone: string
}
export interface GetInvitePhoneParams {
  inviteId: string
}
export interface DelCardParams {
  reURL: string
}
